---
name: Deploy Jenkins jobs
on:
  push:
    branches:
      - centos-ci
jobs:
  push:
    name: Deploy Jenkins jobs
    runs-on: ubuntu-latest
    if: github.repository == 'nfs-ganesha/ci-tests'
    steps:
      - uses: actions/checkout@v3 
        with:
          ref: 'centos-ci'
      - name: build JJB container image
        run: docker build -t nfs-ganesha-ci-tests -f tests/Containerfile .
      - name: update Jenkins Jobs
        run: docker run --rm --env="JENKINS_API_KEY=${{ secrets.JENKINS_API_KEY2 }}" --entrypoint=tests/deploy-nfs-ganesha-ci.sh nfs-ganesha-ci-tests:latest
